[client]
showSidebarNavigation = false

[server]
port = 8501
baseUrlPath = "/landscaping"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor="#064475"