
# Top-level directory paths (used across all modules)
root_dir: "/home/lcheng/oz318/research-link-technology-landscaping"
data_dirname: "data"
logs_dirname: "logs"

# Data configuration
data:
  grants_file: "active_grants.json"


# Modeling workflow configuration
modeling:
  # Default model for all LLM tasks
  default_model: "openai/gpt-4o-mini"
  
  # Step 1: Keywords Extraction
  extraction:
    # Number of keywords to extract per category
    keywords_per_category: 8
    max_keywords_per_category: 10
    min_keywords_per_category: 5
    
    # Prompt configuration
    system_message: |
      You are an expert research analyst with deep knowledge across multiple academic disciplines and a keen eye for emerging research trends. 
      Your task is to extract meaningful keywords from research grant information that would be useful for:
      - Identifying emerging research domains and interdisciplinary areas
      - Discovering novel methodologies and cutting-edge approaches
      - Tracking innovative technologies and emerging tools
      - Finding related research projects working on similar frontiers
      - Understanding emerging research trends and future directions

      Focus on extracting keywords that highlight what's new, innovative, and emerging in the research landscape. Prioritize:
      - Technical terms that represent novel concepts or emerging fields
      - Methodologies that are cutting-edge or represent new approaches
      - Technologies that are innovative or represent emerging tools
      - Applications that address new challenges or emerging needs
      - Scientific terminology that indicates research at the frontiers of knowledge

      Provide accurate, specific, and well-categorized keywords that capture the innovative and emerging aspects of the research.
    
    focus_areas:
      - "emerging research domains and interdisciplinary areas"
      - "novel methodologies and cutting-edge approaches"
      - "innovative technologies and emerging tools"
      - "novel applications and emerging needs"
      - "new scientific concepts and terminology"
    
    keyword_categories:
      - name: "keywords"
        description: "most relevant keywords capturing the research content"
      - name: "methodology_keywords"
        description: "keywords related to research methodologies or approaches"
      - name: "application_keywords"
        description: "keywords related to target applications or outcomes"
      - name: "technology_keywords"
        description: "keywords related to technologies or tools mentioned"
    
  # Step 2: Keywords Harmonisation
  harmonisation:
    # Prompt configuration
    system_message: |
      You are an expert in research terminology and knowledge organization with deep understanding of scientific vocabulary across disciplines.

      Your task is to harmonise a list of research keywords by:
      1. Identifying and merging similar keywords, variants, and synonyms
      2. Standardizing terminology using the most commonly accepted scientific terms
      3. Resolving inconsistencies in naming conventions
      4. Preserving the semantic richness while reducing redundancy

      Guidelines:
      - Merge keywords that are clearly variants of the same concept
      - Use the most standard, widely-accepted term when merging
      - Preserve technical precision - don't over-generalize
      - Maintain the granularity level appropriate for research analysis
      - Keep domain-specific terminology when it adds value
      
      Remember: This is about cleaning up keyword variants, NOT about creating higher-level topic categories or abstractions.
    
    instructions:
      - "Identify and merge similar keywords, variants, and synonyms"
      - "Standardize terminology using commonly accepted scientific terms"
      - "Resolve inconsistencies in naming conventions"
      - "Preserve semantic richness while reducing redundancy"
      - "Use the most standard, widely-accepted term when merging"
      - "Preserve technical precision - don't over-generalize"
      - "Maintain appropriate granularity level for research analysis"
    
  # Step 3: Keyword Assignment
  assignment:
    # This step assigns harmonised keywords to grants based on extracted keywords
    # No configurable parameters - behavior is implemented directly in the pipeline

# Web dashboard configuration
web:
  title: "Research Technology Landscaping Dashboard"
  icon: "🔍"
  layout: "wide"


