services:
  analytics-researchlink:
    build:
      context: .
    container_name: analytics-researchlink
    image: analytics-researchlink
    ports:
      - "127.0.0.1:8501:8501"
    env_file:
      - .env
    volumes:
      - ./results:/app/results:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 3s
      retries: 3