extract: 
	uv run inspect eval extract.py@extract --limit 100

harmonise:
	uv run inspect eval harmonise.py@harmonise

categorise: 
	uv run inspect eval categorise.py@categorise

coarsen:
	uv run inspect eval coarsen.py@coarsen

refine:
	uv run inspect eval refine.py@refine

merge:
	uv run inspect eval merge.py@merge

classify: 
	uv run inspect eval classify.py@classify --limit 10

.PHONY: extract categorise coarsen refine classify