[project]
name = "modeling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inspect-ai>=0.3.123",
    "jupyter>=1.1.1",
    "neo4j>=5.28.2",
    "openai>=1.99.9",
    "pandas>=2.3.1",
    "plotly-express>=0.4.1",
    "pyarrow>=21.0.0",
    "pyrla",
]

[tool.uv.sources]
pyrla = { path = "../pyrla" }
